### ISSUE TITLE
Include path issue with strawberry perl?

### ISSUE THREAD

**Issue by toddr** [akiym/Crypt-OpenSSL-Guess#4]
I’m not sure if this is a missing library issue for a bad guess. 

http://www.cpantesters.org/cpan/report/f0516f3e-6c12-1014-9a47-6eab8038f308

**Comment by akiym** [comment]
Perhaps it's Crypt::OpenSSL::RSA problem :)
I have looked into CPAN testers reports for Crypt::OpenSSL::RSA@0.28 on Windows, it seems they have same build error on perl-5.26 or later.

http://matrix.cpantesters.org/?dist=Crypt-OpenSSL-RSA%200.28
http://www.cpantesters.org/cpan/report/5d014410-6bfa-1014-82a9-b3d262ca88c4

**Comment by rurban** [comment]
They are not linking against `-lssl -lcrypto` at all. All this was fixed with my 0.29 version.

**Comment by toddr** [comment]
I've added appveyor so we have more visibility. https://ci.appveyor.com/project/toddr/crypt-openssl-rsa

It is my impression that Crypt::OpenSSL::Guess would need to specify -lcrypto since that's its area of responsibility? Or am I misunderstanding here?

**Comment by toddr** [comment]
Re-read the makefile. -lcrypto is my responsibility. My bad. closing.
