### ISSUE TITLE
use `brew --prefix` for OPENSSL_PREFIX if available

### ISSUE THREAD

**Issue by skaji** [akiym/Crypt-OpenSSL-Guess#5]
I think it's worth Crypt-OpenSSL-Guess having this logic too https://github.com/radiator-software/p5-net-ssleay/pull/158

**Comment by cdalvaro** [comment]
With Apple Silicon Homebrew installs by default in `/opt/homebrew` directory.

For Apple M1 machines, making those changes will fix the installation of this module.
