### ISSUE TITLE
Syntax error in Guess.pm

### ISSUE THREAD

**Issue by ananiketgd** [akiym/Crypt-OpenSSL-Guess#6]
Below line is having syntax error at **$dir/p->[1].lib**. This should have **$p** instead of just **p**.
https://github.com/akiym/Crypt-OpenSSL-Guess/blob/master/lib/Crypt/OpenSSL/Guess.pm#L52

**Comment by akiym** [comment]
Good catch. I need to backport from the latest Net::SSLeay.
